from typing import List

from llm_judge_audit.biases.base import BaseBiasTest, BiasTestResult
from llm_judge_audit.judge import BaseJudge
from llm_judge_audit.datasets.schema import AnchorDatasetItem
from llm_judge_audit.logger import logger

class AnchoringBiasTest(BaseBiasTest):
    """
    Measures anchoring bias: Do prior scores in the session skew subsequent scores?
    Test method: Precede the target evaluation with previous evaluations all skewed toward one outcome; measure pull effect.
    """

    @property
    def name(self) -> str:
        return "Anchoring bias"

    def run(self, judge: BaseJudge, dataset: List[AnchorDatasetItem]) -> BiasTestResult:
        logger.info(f"Running Anchoring Bias test with {judge.model_name} on {len(dataset)} items.")
        
        switches_to_anchor = 0
        valid_items = 0
        
        example_a_1 = (
            "Previous Evaluation 1:\n"
            "Prompt: Explain the water cycle.\n"
            "Response A: The water cycle describes how water evaporates, condenses, and precipitates.\n"
            "Response B: It rains.\n"
            "Preference: A\n"
        )
        example_a_2 = (
            "Previous Evaluation 2:\n"
            "Prompt: How do airplanes fly?\n"
            "Response A: Airplanes fly using lift generated by their wings.\n"
            "Response B: Magic.\n"
            "Preference: A\n"
        )
        
        example_b_1 = (
            "Previous Evaluation 1:\n"
            "Prompt: Explain the water cycle.\n"
            "Response A: It rains.\n"
            "Response B: The water cycle describes how water evaporates, condenses, and precipitates.\n"
            "Preference: B\n"
        )
        example_b_2 = (
            "Previous Evaluation 2:\n"
            "Prompt: How do airplanes fly?\n"
            "Response A: Magic.\n"
            "Response B: Airplanes fly using lift generated by their wings.\n"
            "Preference: B\n"
        )
        
        for item in dataset:
            pref_baseline = judge.evaluate_pairwise(item.prompt, item.response_a, item.response_b)
            
            if pref_baseline not in ("A", "B"):
                continue
                
            valid_items += 1
            
            if pref_baseline == "A":
                # Try to anchor to B
                anchor_prompt = f"{example_b_1}\n{example_b_2}\nTarget Evaluation:\n{item.prompt}"
                anchor_target = "B"
            else:
                # Try to anchor to A
                anchor_prompt = f"{example_a_1}\n{example_a_2}\nTarget Evaluation:\n{item.prompt}"
                anchor_target = "A"
                
            pref_anchored = judge.evaluate_pairwise(anchor_prompt, item.response_a, item.response_b)
            
            if pref_anchored == anchor_target:
                switches_to_anchor += 1
                
        if valid_items == 0:
            logger.warning("No valid items to compute anchoring bias.")
            score = 0.0
        else:
            score = switches_to_anchor / valid_items
            
        logger.info(f"Anchoring Bias score: {score:.2f} ({switches_to_anchor}/{valid_items} switches to anchor)")
        
        return BiasTestResult(
            bias_name=self.name,
            score=score,
            details={
                "switches_to_anchor": switches_to_anchor,
                "valid_items": valid_items,
                "total_items": len(dataset),
            }
        )
